Friends -Likes
TeDixxx/java-filmorate pull request #9
Opened 2023-03-03 14:00 UTC by TeDixxx

2023-03-03 20:08 UTC, db-exp requested changes

2023-03-03 20:08 UTC, db-exp commented on src/test/java/ru/yandex/practicum/filmorate/UserServiceTest.java
> +    User user = new User( 1,"xxx.@mail.ru","xxx","dmitry",
такие вещи лучше делать в методе с Before аннотацией

2023-03-03 20:08 UTC, db-exp commented on src/test/java/ru/yandex/practicum/filmorate/FilmServiceTest.java
> +//    Film film = new Film(1,"xxx","xxx",LocalDate.of(2000,12,1),200);
давай удалим ненужное

2023-03-04 07:48 UTC, TeDixxx commented on src/test/java/ru/yandex/practicum/filmorate/UserServiceTest.java
> +    User user = new User( 1,"xxx.@mail.ru","xxx","dmitry",
суть в том, что у меня их нет... Я их еще в самом начале удалил.. Я не знаю как они тут оказались

2023-03-05 07:48 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    public boolean checkValid(User user) {
все таки такие вещи лучше через spring-validation обрабатывать - меньше кода, меньше возможностей ошибиться и больше возможностей проверки

2023-03-05 07:49 UTC, db-exp approved these changes

2023-03-27 08:49 UTC, closed without merging